### ISSUE TITLE
前端：确定接口规格

### ISSUE THREAD

**Issue by buaaFlamenco** [buaaFlamenco/rateMyCourse#11]

**Comment by buaaFlamenco** [comment]
关于这一点，Django中常用的方法是在views.py里面直接import models，然后用获得的数据填模板。但我觉得这样的耦合度太高。所以我想在中间多一个环节interface.py，views.py只需import interface，这个文件里面有所需的接口，能够轻松调用。所以这个issue要做的就是确定这个interface的规格，然后后端完成它。

**Comment by itsumu** [comment]
@buaaFlamenco 
Iterface.py已签入
