### ISSUE TITLE
开发前准备：Django环境搭建

### ISSUE THREAD

**Issue by Liu-SD** [buaaFlamenco/rateMyCourse#15]

**Comment by Liu-SD** [comment]
用了将近一个星期的时间把Django的入门教程大致看了一遍。数据库那一部分的一些字段的使用还是不太理解，后续实践中再进一步加深理解。

**Comment by Donemeb** [comment]
本地Django环境基本搭建完毕，其中STATIC全局变量的设置仍存在问题。
