### ISSUE TITLE
开发前准备：前端框架学习

### ISSUE THREAD

**Issue by Liu-SD** [buaaFlamenco/rateMyCourse#16]

**Comment by itsumu** [comment]
对前端开发三大语言的职能进行了了解：
1.HTML负责网页部件的部署
2.CSS负责网页静态部分的外观美化
3.Javascript负责网页动态部分的展示与操作

个人理解三者的开发顺序应该是：HTML->CSS->Javascript
HTML是一切的源头，正在学习HTML常用标签

**Comment by itsumu** [comment]
推荐学习网站 [http://www.w3school.com.cn/](http://www.w3school.com.cn/)
简洁、免费、可实时预览代码进行练习

**Comment by zhaobs-yu** [comment]
先学习界面原型设计，这里使用的工具是mockplus, 操作比较简单。之后学习网页的具体实现，使用的开发工具是pingendo, 现阶段主要用HTML和CSS进行页面设计。

**Comment by Lydia-yang** [comment]
学习了html、css和javascript，通过html先搭建一个框架，css进行各个部件的外观设计，再最后能够通过javascrip实现响应功能，个人认为比较难的是前后端的连接。
