### ISSUE TITLE
前端：搜索结果与评价页面布局重构

### ISSUE THREAD

**Issue by itsumu** [buaaFlamenco/rateMyCourse#37]

**Comment by itsumu** [comment]
具体布局参照[issue 38](https://github.com/buaaFlamenco/rateMyCourse/issues/38)

**Comment by zhaobs-yu** [comment]
https://github.com/buaaFlamenco/rateMyCourse/commit/63167154854dea6eb119694c286d4b378559e41d
https://github.com/buaaFlamenco/rateMyCourse/commit/8840b55c9d81629ff32c63eaecfa9c7817e32e73

**Comment by zhaobs-yu** [comment]
mission completed
