### ISSUE TITLE
前端：用户信息页面

### ISSUE THREAD

**Issue by Liu-SD** [buaaFlamenco/rateMyCourse#47]
设计以及初步搭建，包括新消息提醒

**Comment by itsumu** [comment]
![32228ddb6d7e41ea94a3a358500be60b](https://user-images.githubusercontent.com/19208101/33364905-59d6e2e4-d521-11e7-8c88-902c064ca693.jpg)
![72655f35b2ca3ff3d43d84292f4b578e](https://user-images.githubusercontent.com/19208101/33364908-5e600e26-d521-11e7-9953-46848511d9ac.jpg)
![d96d99110a3d6e7831a39bf883019f7e](https://user-images.githubusercontent.com/19208101/33364912-61ca4b3a-d521-11e7-89bd-7338c555bed7.jpg)
用户界面原型图设计完成

**Comment by itsumu** [comment]
用户信息页面模板已完成
[https://github.com/buaaFlamenco/rateMyCourse/commit/4c3b33d759a69dc11570423391b45092f1581df9](https://github.com/buaaFlamenco/rateMyCourse/commit/4c3b33d759a69dc11570423391b45092f1581df9)
