### ISSUE TITLE
网站界面整体美化与优化

### ISSUE THREAD

**Issue by Liu-SD** [buaaFlamenco/rateMyCourse#62]

**Comment by itsumu** [comment]
[https://github.com/buaaFlamenco/rateMyCourse/commit/61e40caee4a92b2e8e813b548e5cfd055015bb01](https://github.com/buaaFlamenco/rateMyCourse/commit/61e40caee4a92b2e8e813b548e5cfd055015bb01)
引入新的模板css，增加镂空圆角设计与导航栏透明、滚动式渐变的设计
